# Generated by Django 4.1.6 on 2023-03-08 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mechanism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiarBidder',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanism.auction')),
                ('liar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
