# Generated by Django 4.1.6 on 2023-03-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanism', '0002_auction_open_close_auction_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin_A',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin_B',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin_C',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_inventory_incharge',
            field=models.BooleanField(default=False),
        ),
    ]
