# Generated by Django 4.1.6 on 2023-03-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanism', '0003_user_is_admin_a_user_is_admin_b_user_is_admin_c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='product_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
