# Generated by Django 4.1.6 on 2023-03-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanism', '0003_notsettledauction_arrived_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminwaitingauction',
            name='semaphore',
            field=models.CharField(blank=True, default='000', max_length=5, null=True),
        ),
    ]
