# Generated by Django 4.1.6 on 2023-03-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanism', '0004_alter_adminwaitingauction_semaphore'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='citizenship_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
