# Generated by Django 4.1.6 on 2023-03-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanism', '0004_auction_product_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='AuctionImages/'),
        ),
        migrations.DeleteModel(
            name='AuctionImage',
        ),
    ]
