# Generated by Django 4.1.6 on 2023-03-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanism', '0005_auction_thumbnail_delete_auctionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='semaphore',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
