# Generated by Django 4.1.1 on 2022-10-08 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biduser',
            name='bio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biduser',
            name='latitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biduser',
            name='longitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biduser',
            name='phone_num',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='biduser',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='biduser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='biduser',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='ProfileImages/'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('0', 'Poor'), ('1', 'Satisfactory'), ('2', 'Good'), ('3', 'Better'), ('4', 'Excellent')], default='0', max_length=1)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
