# Generated by Django 4.1.1 on 2022-10-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_biduser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('0', 'No rating'), ('1', 'Poor'), ('2', 'Satisfactory'), ('3', 'Good'), ('4', 'Better'), ('5', 'Excellent')], default='3', max_length=1),
        ),
    ]
