# Generated by Django 4.1.1 on 2022-10-09 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0002_alter_bids_id_alter_estate_id_alter_estateimage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bid_list', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
