# Generated by Django 4.1.1 on 2022-10-10 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0003_bids_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='auction',
        ),
        migrations.AddField(
            model_name='notification',
            name='bid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.bids'),
        ),
        migrations.AddField(
            model_name='notification',
            name='estate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.estate'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_like',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='other_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
