# Generated by Django 4.1.1 on 2022-10-10 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_notification_other_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.bids'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.estate'),
        ),
    ]
