# Generated by Django 4.1.1 on 2022-10-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_notification_bid_alter_notification_estate'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_checked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
